### ISSUE TITLE
Mods tab issues with SMLHelper installed

### ISSUE THREAD

**Issue by LeeTwentyThree** [SubnauticaModding/Nautilus#314]
https://github.com/SubnauticaModding/Nautilus-Proto/issues/32

Issue mirrored @RamuneNeptune

**Comment by 32Kallies** [comment]
Seems serious, but I can't recreate it. Feel free to make a new issue report if you find it again with current versions and can find steps to reproduce.

**Comment by 32Kallies** [comment]
https://github.com/SubnauticaModding/Nautilus/pull/329

**Comment by 32Kallies** [comment]
Resolved.
