### ISSUE TITLE
ConfigFile button methods/actions not working

### ISSUE THREAD

**Issue by LeeTwentyThree** [SubnauticaModding/Nautilus#315]
https://github.com/SubnauticaModding/Nautilus-Proto/issues/31

Issue mirrored @RamuneNeptune

**Comment by 32Kallies** [comment]
Seems to work as intended.

Make sure you include a parameter of type `ButtonClickedEventArgs` in the button method, i.e.
```cs
OnClick(ButtonClickedEventArgs e)
{
    // ...
}
```
