### ISSUE TITLE
CraftTreeHandler.AddTabNode issue with tab names

### ISSUE THREAD

**Issue by LeeTwentyThree** [SubnauticaModding/Nautilus#319]
https://github.com/SubnauticaModding/Nautilus-Proto/issues/26

Issue mirrored @RamuneNeptune

**Comment by RamuneNeptune** [comment]
Issue seems to be happening again


![](https://i.imgur.com/Q1YkmYm.png)
![](https://i.imgur.com/hQ7tXqj.png)

**Comment by RamuneNeptune** [comment]
Okay seems to be only an issue when adding a tab to a tab

 1. "Resources" -> "Alloys"
 2. "Resources" -> "Alloys" & "Electronics"
 3. "Resources" (no child tabs) 

1 and 2 have the issue, whereas 3 which is just a standalone tab node with a crafting node, does not have the issue
This also shows that tab nodes having child tab nodes don't seem to work, and the only nodes displayed are the child tab nodes

**Comment by 32Kallies** [comment]
I really can't recreate this issue, just tried and it works perfectly. Do you have any code I can test with?

**Comment by MrPurple6411** [comment]
@RamuneNeptune are you by chance using the AddTabNode(string nameID) that does not set the language lines for the tab nodes?
