### ISSUE TITLE
Asset Bundle documentation

### ISSUE THREAD

**Issue by 32Kallies** [SubnauticaModding/Nautilus#334]
**Describe the feature**
- Broad asset bundle guide.
- Specific asset bundle tutorial (add a craftable item).

**Purpose**
These are useful.

**Usage**
Nautilus documentation.

**Comment by EldritchCarMaker** [comment]
https://github.com/EldritchCarMaker/Nautilus/blob/docs/Nautilus/Documentation/tutorials/Custom-Objects.md I got started on a page for this, and havent had the chance or motivation to work on it much more. I'd be able to give the unity project for someone else to finish up the guide though. At this point, its just down to getting the thing in game, which is just loading from bundle

**Comment by 32Kallies** [comment]
I'd be fine doing both
