### ISSUE TITLE
List vanilla steps to fabricator tabs in docs

### ISSUE THREAD

**Issue by 32Kallies** [SubnauticaModding/Nautilus#336]
**Describe the feature**
Something like this but in Nautilus docs:
[craft-trees.txt](https://github.com/SubnauticaModding/Nautilus/files/11483396/craft-trees.txt)

**Purpose**
How else are you supposed to find it?

**Comment by EldritchCarMaker** [comment]
Via the CraftTree class?

**Comment by 32Kallies** [comment]
Which is quickly viewable through a browser or IDE?

**Comment by 32Kallies** [comment]
Although I am curious as to what you did in the past. Personally I just looked at English.json or example mods.

**Comment by 32Kallies** [comment]
Also maybe I’ll link the created documentation page in relevant method documentation

**Comment by RamuneNeptune** [comment]
> Although I am curious as to what you did in the past. Personally I just looked at English.json or example mods.

`CraftTree` class in dnSpy

**Comment by 32Kallies** [comment]
Then yeah you shouldn’t have to decompile something every time you want to add an item. Things need to be more streamline.

**Comment by RamuneNeptune** [comment]
It's pretty negligible, the comparison is:
  - Open dnSpy, and type `CraftTree`
  - Open the docs, and find the `CraftTree` list
  
Still, would be a positive addition to the docs

**Comment by MrJumpscare** [comment]
Also because people might not know it can be found in CraftTree, and with the docs being much smaller than the SN source code, its more likely people will find it.

**Comment by 32Kallies** [comment]
Completed #339
