### ISSUE TITLE
Always return prefabs as active (unless this causes issues)

### ISSUE THREAD

**Issue by 32Kallies** [SubnauticaModding/Nautilus#358]
**Describe the feature**
Patch the method that spawns constructables and make sure they are active if needed.

**Comment by EldritchCarMaker** [comment]
Wouldn’t it be easier to just set the prefab active in one of the prefab handling methods? There’s already a lot of things like setting fields on prefab identifiers, so it could fit there

**Comment by 32Kallies** [comment]
Maybe. Needs testing

**Comment by 32Kallies** [comment]
Will be considered in #364
