### ISSUE TITLE
Options panel is not patched when SMLHelper is installed

### ISSUE THREAD

**Issue by 32Kallies** [SubnauticaModding/Nautilus#378]
**Describe the bug**
"If SMLHelper is installed, the options panel doesn't get patched. This is unrelated to the controller fixes and seems to be intentional, Nautilus checks it in OptionsPanelPatcher before patching."

Reported by @celvro.

**Comment by 32Kallies** [comment]
How critical is this?

**Comment by celvro** [comment]
Depends on how many people are using both. I'm not sure it's even fixable unless we can undo SMLHelper's patches and apply these instead. Think it's possible to prefix the SML options patcher and skip it?
