### ISSUE TITLE
Tech analysis on pickup is not verbose (BASE GAME ISSUE)

### ISSUE THREAD

**Issue by 32Kallies** [SubnauticaModding/Nautilus#380]
**Describe the bug**
When picking up an item that is intended to unlock a blueprint, you will receive no visual or auditory feedback at all.

**To Reproduce**
1. Create a new survival save file.
2. Try to pick up a creature. This should ideally give you a notification for unlocking the cooked/cured recipes.
3. Notice how there is no analysis tech notification at all.

**Expected behavior**
Blueprint analysis notifications should appear on pickup for items where they were added intentionally.

**Comment by 32Kallies** [comment]
We have reached out to UWE. If we don't receive any answer within a week or so, we will consider fixing this on our own. Or if this change was intentional, we will still allow modded items to have notifications.

**Comment by vlyon** [comment]
After some careful testing, I have found this patch to work well:
```c#
// This patch fixes a bug in Subnautica that silences notifications like unlocked blueprints
[HarmonyPatch(typeof(Pickupable), nameof(Pickupable.Pickup))]
class Pickupable_Pickup_Patch
{
    static void Postfix(Pickupable __instance, bool events)
    {
        if (events)
            KnownTech.Add(__instance.GetTechType());
    }
}
```
Maybe we could check the game version and _only_ patch versions known to have the bug?

**Comment by 32Kallies** [comment]
I am really considering just patching this. It seems unintentional and I have not heard back from UWE.

**Comment by vlyon** [comment]
I **really** believe this is not intentional.
Maybe we could _only_ implement the patch if `SNUtils.GetPlasticChangeSetOfBuild() == 71288` or by comparing `SNUtils.GetDateTimeOfBuild()` with the time of the release of Nautilus.

**Comment by 32Kallies** [comment]
> I **really** believe this is not intentional. Maybe we could _only_ implement the patch if `SNUtils.GetPlasticChangeSetOfBuild() == 71288` or by comparing `SNUtils.GetDateTimeOfBuild()` with the time of the release of Nautilus.

Absurd that it's still not fixed after reaching out to them. We should definitely do that, thanks for the suggestions.

**Comment by 32Kallies** [comment]
Personally I think a transpiler in the `Inventory.Pickup` method is the best way to go about fixing this, but I am really bad when it comes to making those

**Comment by 32Kallies** [comment]
Not a Below Zero bug but working on a fix now
