### ISSUE TITLE
ModButtonOption does not have a tooltip

### ISSUE THREAD

**Issue by tinyhoot** [SubnauticaModding/Nautilus#387]
**Describe the bug**
When trying to create a ModButtonOption without the attribute-based system it is impossible to create a tooltip for the button. It seems that ModButtonOption.cs is the only ModOptions class without a Tooltip field and a tooltip argument is also missing from its `ModButtonOption.Create()` method, which is inconsistent with every other ModOption.

**To Reproduce**
1. Go to IDE
2. Try to use `ModButtonOption.Create()` with `tooltip = "my cool tooltip"`
3. Get yelled at by the compiler

**Expected behavior**
Being able to add a tooltip to a button just like any other option.

**Comment by 32Kallies** [comment]
It appears that there is no way to add tooltips for buttons in the base game, as opposed to the other options.

**Comment by JKohlman** [comment]
Neither did the color picker iirc so it should be easy enough to add templated on that one
