### ISSUE TITLE
Logging discrepancies, DEBUG/WARNING is logging as INFO in specific cases

### ISSUE THREAD

**Issue by RamuneNeptune** [SubnauticaModding/Nautilus#395]
**Describe the bug**
- `InternalLogger.Debug("")`, will ***incorrectly*** log to console as INFO, I believe because it's using `Console.WriteLine`
- `InternalLogger.Log("", LogLevel.Debug)`, will correctly log to console as DEBUG
<br>

**What I've found that is affected by this**
```ini
[Info   :   Console] [Nautilus/Error] Failed to add ... to ... as it is not a registered combination.
[Info   :   Console] [Nautilus/Error] Error on LoadTextureFromFile call. File not found at ...
[Info   :   Console] [Nautilus/Debug] Added "..." to groups under "..."
[Info   :   Console] [Nautilus/Debug] PingTypePatcher is initialized.
[Info   :   Console] [Nautilus/Debug] TechTypePatcher is initialized.
[Info   :   Console] [Nautilus/Debug] CraftTreeTypePatcher is initialized.
[Info   :   Console] [Nautilus/Debug] Successfully added PingType: '...' to Index: '...'
[Info   :   Console] [Nautilus/Debug] Successfully added TechType: '...' to Index: '...'
[Info   :   Console] [Nautilus/Debug] Successfully added CraftTreeType: '...' to Index: '...'
[Info   :   Console] [Nautilus/Debug] '...' will be added to the custom craft tree '...'
[Info   :   Console] [Nautilus/Debug] [...] [Options] Found ... options to add to the menu.
[Info   :   Console] [Nautilus/Debug] [...] [Options] OptionsMenuBuilder metadata parsed in 5ms.
```

**Comment by 32Kallies** [comment]
Want to make a PR for this? I have a million issues on my plate already.

**Comment by 32Kallies** [comment]
Definitely an issue but can't be fixed with how it is currently set up because `Logger.Log` cannot be called when `Initialized` is false, because that is only false when the logger doesn't exist.

**Comment by 32Kallies** [comment]
Now actually, we could create a new log source for Nautilus that is initialized early, but that is very low priority compared to our other issues.

**Comment by LeeTwentyThree** [comment]
I had to build the example mod for that to work. However, I thought we were making this an automatic process for all mods. Is this not the case?

**Comment by LeeTwentyThree** [comment]
Regardless, seems to work as intended.

**Comment by 32Kallies** [comment]
I had the wrong tab open ... oops

**Comment by 32Kallies** [comment]
Anyway, I don't think this is something we can easily fix, since the root of the problem is that the logger does *not* exist when we try to use it.
