### ISSUE TITLE
Seamoth Won't Move

### ISSUE THREAD

**Issue by lizardguts73** [SubnauticaModding/Nautilus#425]
**Describe the bug**
Seamoth doesn't have any propulsion when theres an upgrade module in it while loading into a save.

**To Reproduce**
1. For me I just put the mk1 depth module into the seamoth and then save the game and exit the save.
2. Then when you load back into the save the seamoth won't be able to move anymore.
3. If there are no upgrade modules inside of the seamoth while loading in the seamoth will function as intended.

**Expected behavior**
I expected the seamoth to be able to move no matter what upgrade modules I had in it.

This is what comes up in the log when trying to move the seamoth.

[Warning: Unity Log] Kinematic body only supports Speculative Continuous collision detection
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Vehicle.ApplyPhysicsMove () (at <9ec6c1b62c324758b9c2d79021505be6>:0)
Vehicle.FixedUpdate () (at <9ec6c1b62c324758b9c2d79021505be6>:0)
SeaMoth.FixedUpdate () (at <9ec6c1b62c324758b9c2d79021505be6>:0)

The only mods I have installed are Nautilus and SubnauticaModManager. I went through my entire mod list to figure out which one was causing the problem. As soon as Nautilus is removed the bug goes away and the seamoth works again.

**Comment by lizardguts73** [comment]
I was using the latest pre release version 1.0.0-pre.14

**Comment by VELD-Dev** [comment]
Uh oh... Is it because of the new gadget I made? I'll try that

**Comment by 32Kallies** [comment]
A fix for this (#426) should be included in the [1.0.0-pre.15 release](https://github.com/SubnauticaModding/Nautilus/releases/tag/1.0.0-pre.15). Feel free to re-open this issue or open a new issue if the problem still occurs.

**Comment by toebeann** [comment]
Worth mentioning you may need to remove and reinsert upgrade modules in the seamoth for it to work correctly again.
