### ISSUE TITLE
SMLHelper and Nautilus fight over recipe changes

### ISSUE THREAD

**Issue by tinyhoot** [SubnauticaModding/Nautilus#431]
**Describe the bug**
SMLHelper and Nautilus interact in a way that causes the logoutput.log to balloon to incredible sizes when two mods try to modify the same recipe. Because both SML and Nautilus patch CraftData.Get() and check whether their recipe is currently loaded, this causes an infinite back and worth between the two. The log entries created in the process ("Replaced x existing entries to the CraftData.techData dictionary") go on forever.

**To Reproduce**
1. Install SMLHelper and Nautilus
2. Install one recipe altering mod each (in my case, Deathrun for SML and SubnauticaRandomiser for Nautilus). The mods must modify the same recipe
3. Load into a game
4. Do anything that makes the game call `CraftData.Get()` like opening the blueprints tab or interacting with a fabricator
5. Observe the log

**Expected behavior**
Both mods patch once, with one of them winning the tie.

**Log**
The issue starts appearing around line 2700.
[LogOutput.log](https://github.com/SubnauticaModding/Nautilus/files/11945932/LogOutput.log)

**Comment by MrPurple6411** [comment]
As of Today SMLHelper is fully depreciated and will be Legacy Only.
Please convert to Nautilus.
