### ISSUE TITLE
Incorrect class in custom module tutorial

### ISSUE THREAD

**Issue by Indigocoder1** [SubnauticaModding/Nautilus#436]
During the custom module tutorial on the Nautilus page the tutorial uses the wrong class for .SetRecipe.

**To Reproduce**
Go to https://subnauticamodding.github.io/Nautilus/tutorials/vehicle-module.html
Scroll down to where it says "Now, let's quickly set the basic settings."

**Expected behavior**
The class that has the .SetRecipe function is the CustomPrefab class

**Screenshots**
![image](https://github.com/SubnauticaModding/Nautilus/assets/130301845/9fdcf7c1-a863-4253-9925-341e015fe63b)

**Comment by 32Kallies** [comment]
Fixed.
