### ISSUE TITLE
StoryGoal Custom Events do not receive name of triggering goal

### ISSUE THREAD

**Issue by tinyhoot** [SubnauticaModding/Nautilus#475]
**Describe the bug**
When registering a callback for a StoryGoal, the documentation notes that the callback is meant to receive the name of the goal when it is invoked. This enables reusing the same method for multiple custom events. However, the method signature requires an `Action` rather than an `Action<string>` and the event is similarly invoked without the goal name.

**To Reproduce**
1. See [RegisterCustomEvent()](https://github.com/SubnauticaModding/Nautilus/blob/master/Nautilus/Handlers/StoryGoalHandler.cs#L140) and [NotifyGoalComplete()](https://github.com/SubnauticaModding/Nautilus/blob/master/Nautilus/MonoBehaviours/CustomStoryGoalManager.cs#L71)
2. Try using an `Action<string>` anyway
3. Be sad as the compiler yells at you

**Expected behavior**
Get the goal name on unlock.

**Comment by Metious** [comment]
This looks like a mistake and overlook in the documentation. The initial implementation of the `RegisterCustomEvent` method only took an `Action<string>` as a parameter, but we eventually scrapped that for the current implementation, which can be seen [here](https://github.com/SubnauticaModding/Nautilus-Proto/pull/8/commits/a98d787e6fca362f9026f0e9f3957d8594987534). 

I don't remember why exactly we did that, that's the issue with Discord discussion I suppose, but I think the best way to go about this is to fix the documentation for the current methods, then add back the `Action<string>` overload.
That way we wont have any breaking changes, and we would also support one callback-for-all kind of custom goal handling.
