### ISSUE TITLE
If an mod item is setting the SetUnlock but the techtype that unlocks it is unlocked by default then it should unlock by default.

### ISSUE THREAD

**Issue by MrPurple6411** [SubnauticaModding/Nautilus#479]
Currently if you set the unlock type of a mod item to .... lets say the Fabricator, then nothing you can do will unlock the object as you cannot pickup a fabricator and if you don't set it to be scannable then it just can't be scanned.

Now Normally I would just say.... well don't set that as the scan type BUT I interestingly stumbled upon a use case for changing this.

Now with my Basekits mods I am setting the cloned type to require the original to be unlocked and as such I am running up against this issue.

If I leave it as they are just auto unlocked, then if someone actually locks the originals then mine are still unlocked but if we tell nautilus to check if the things are already unlocked while we are patching them into the games initialize then it won't matter if someone else changes it because the following one will then use the correct unlock.

**Screenshots**
![image](https://github.com/SubnauticaModding/Nautilus/assets/7858500/2c581645-8477-4f06-9447-429cf60d07b5)

**Comment by Metious** [comment]
Fixed as of 1.0.0-pre.22
