### ISSUE TITLE
Module gadgets don't work

### ISSUE THREAD

**Issue by Indigocoder1** [SubnauticaModding/Nautilus#491]
**Describe the bug**
When using the module gadget `(myPrefab.SetVehicleUpgradeModule`) the event for `.WithOnModuleUsed` doesn't work, and cooldowns seem to be broken. Power is still taken but you can spam the module even when setting a cooldown with `.WithColdown`

**To Reproduce**
1. Make a custom item
2. Use `.SetWehicleUpgradeModule` on the `CustomPrefab`, then use the `.WithOnModuleUsed` extension
3. Enter the game and install the module
4. Using the module does not have the desired effect

**Expected behavior**
The module should have a cooldown and run the code inside `.WithOnModuleUsed`

**Screenshots**
This is the code I've used which does not work
![image](https://github.com/SubnauticaModding/Nautilus/assets/130301845/09df000a-7e58-4989-bc44-41fee40a9446)

**Comment by Metious** [comment]
This bug seems to be only noticeable for the Seamoth because it doesn't call back to the base method. This issue will be fixed in the next release, however, if this module is supposed to be for the Seamoth only, consider using the `SeamothModule` equipment type. That one already works fine.

**Comment by xale** [comment]
> if this module is supposed to be for the Seamoth only, consider using the `SeamothModule` equipment type. That one already works fine.

What if I'm trying to make a usable module that's both Seamoth and Prawn compatible?

**Comment by RamuneNeptune** [comment]
Seamoth and Prawn compatible will be fixed in the next release, but he's saying that if you actually only need it work for the Seamoth you can just change it to `EquipmentType.SeamothModule` and it'll work right now
