### ISSUE TITLE
Cannot add Crafting node: YeetKnife as it is being added to Root that contains Tab nodes. VanillaWorkbench, ModdedWorkbench

### ISSUE THREAD

**Issue by wolfred24** [SubnauticaModding/Nautilus#518]
**Describe the bug**
The Nautilus tutorial have the following statement:
customPrefab.SetRecipe(recipe).WithFabricatorType(CraftTree.Type.Workbench);

But that instruction throws the following error:
Cannot add Crafting node: YeetKnife as it is being added to Root that contains Tab nodes. VanillaWorkbench, ModdedWorkbench

In the Nautilus API docs we can find the following info:
https://subnauticamodding.github.io/Nautilus/tutorials/craft-tree-paths.html
Workbench (Modification station):
Not applicable; all crafting nodes are located in the root.

So i dont understand the error because WorkBench nodes are all located at root.
Seems like worckbench have 2 nodes: VanillaWorkbench and ModdedWorkbench.

So code should look like this?
customPrefab.SetRecipe(recipe).WithFabricatorType(CraftTree.Type.Workbench).WithStepsToFabricatorTab("VanillaWorkbench"); ?

**Comment by MrPurple6411** [comment]
hrmm yea we really should just check if its being added to the root and not log the error and just put it in the unsorted tab we made to be used as a fallback

TBH in that instance it wont actually break anything it will just be added to the ModdedWorkbench tab node that we set as a fallback.

you would only add it to VanillaWorkbench if you wanted it 100% to go into the same place as the Vanilla items instead of people being able to tell it is a mod added item.....

**Comment by wolfred24** [comment]
Its not woring at ModdedWorckbench, neither Vainilla one :/
customPrefab.SetRecipe(recipe).WithFabricatorType(CraftTree.Type.Workbench).WithStepsToFabricatorTab("ModdedWorkbench");

![image](https://github.com/SubnauticaModding/Nautilus/assets/25995755/f92b3dfb-6484-4c35-98fd-b44b65bd9d5c)

But now the console isn't showing any error.

**Comment by MrPurple6411** [comment]
> Its not woring at MoodedWorckbench, neither Vainilla one :/ customPrefab.SetRecipe(recipe).WithFabricatorType(CraftTree.Type.Workbench).WithStepsToFabricatorTab("ModdedWorkbench");
> 
> ![image](https://private-user-images.githubusercontent.com/25995755/292643680-f92b3dfb-6484-4c35-98fd-b44b65bd9d5c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMzNjI0NDIsIm5iZiI6MTcwMzM2MjE0MiwicGF0aCI6Ii8yNTk5NTc1NS8yOTI2NDM2ODAtZjkyYjNkZmItNjQ4NC00YzM1LTk4ZmQtYjQ0YjY1YmQ5ZDVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIzVDIwMDkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0ZjkxYjcwYTgxMWRiOWVmNGY4Y2FiMjg2YWQ1MWFlYWYxMzdlZTI2OTViYWQ3MTQ5Y2Y0NTZkOWRiZTA0N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b1LHmt5IfY2ow7XGn2IIQB2pY9uGVFHdKFF56aCcR00)
> 
> But now the console isn't showing any error.

Is your Recipe unlocked by default either using the KnowTechHandler.UnlockOnStart(YourTechType) or by setting the parameter in the PrefabInfo.WithTechType(classId, displayName, description, language: "English", unlockAtStart: true) constructor to allow it to be unlocked.

Easy way to verify is to check if your recipe shows up when in a creative game but not in a survival or freedom save.

**Comment by wolfred24** [comment]
Ohhh im sorry i didnt unlock it at start, i was unaware of that, thanks a lot, i will try :)

**Comment by wolfred24** [comment]
it is now working using the "unlockAtStart: true" as you mention:

`            .WithTechType("YeetKnife", "Yeet Knife", "Powerful knife that makes me go yes.", unlockAtStart: true)
`

![image](https://github.com/SubnauticaModding/Nautilus/assets/25995755/84235bef-1fe4-40f1-a2d8-296f64074f09)

And it is appearing at the Mod Items tab:
![image](https://github.com/SubnauticaModding/Nautilus/assets/25995755/5ec36936-f480-43d1-b8a9-092aeb855e02)


Thanks!

**Comment by wolfred24** [comment]
By the way @MrPurple6411 , I'm aiming to develop a mod to automate resource extraction, gathering and transportation, my main goals are:

1. To create a new "Bot Room" where the user can create bots (also it brings an exit and entrance pipe for those bots), and those bots should have the ability to travel unto certain distances (upgradeable) to collect resources near the base, then they have to return and store those resources in the lockers of the base. Later on I hope to develop the ability for those bots to refill de Bioreactor with resources inside or outside the base, setting priorities. And also to harvest and refill the GrowBeds.
2. A "Resource Transportation Room" that main goal is to transport resources from base to base using Transport Pipes that must be connected between bases in order to transport resources. Just like the oxygen Pipe but instead of transporting oxygen, it will transport resources between bases.

Do u believe this is possible using the actual Nautilus library and other tools? Or it would be better to abandon the idea?

As you can see the main purpose of this mod is to give some sense in having multiple bases all around the map, each one with the ability to gather and transport resources between bases.

**Comment by RamuneNeptune** [comment]
"Do u believe this is possible using the actual Nautilus library and other tools?" you don't need Nautilus to do everything, you do tons of shit without Nautilus
