### ISSUE TITLE
Exception during Nautilus initialization

### ISSUE THREAD

**Issue by kovadam69** [SubnauticaModding/Nautilus#538]
When installing Nautilus in BepInEx I get following exception and no mods are working. The version of Nautilus does not matter, I tried with 1.0.0.21, 1.0.0.29 and now with 1.0.0.27, but I get the exception with all versions.
Have no idea what to do.

**Describe the bug**
[Info   :  Nautilus] Loading v1.0.0.27 for Subnautica
[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000054 (from typeref, class/assembly Atlas, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)
Stack trace:
Nautilus.Patchers.CraftTreePatcher.Patch (HarmonyLib.Harmony harmony) (at <03b551a1b98844cd809c743e49978030>:0)
Nautilus.Initializer..ctor () (at <03b551a1b98844cd809c743e49978030>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.InputSystem.InputSystem:.cctor()

**Expected behavior**
Expected to work

**Screenshots**
Log from BepInEx:
[Message:   BepInEx] BepInEx 5.4.22.0 - Subnautica (2022. 05. 26. 1:27:04)
[Info   :   BepInEx] Running under Unity v2019.4.36.870
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.22.0]
[Info   :   BepInEx] Loaded 1 patcher method from [Tobey.Subnautica.ConfigHandler.Patcher 1.0.2.0]
[Info   :   BepInEx] Loaded 1 patcher method from [Tobey.PluginDoctor.Patcher 0.1.1.0]
[Info   :   BepInEx] Loaded 1 patcher method from [Tobey.UnityAudio.Patcher 2.0.1.0]
[Info   :   BepInEx] 4 patcher plugins loaded
[Info   :Legacy Config Handler] Applying override mode: Default
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Info   :Unity Audio Patcher] Enabling Unity Audio...
[Info   :Unity Audio Patcher] Unity Audio is already enabled, skipping patching.
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 11 plugins to load
[Info   :   BepInEx] Loading [SubnauticaModManager for BepInEx 1.2.2]
[Info   :   BepInEx] Loading [Nautilus 1.0.0.27]
[Info   :   Console] [Nautilus/Info] Enable debug logs set to: False
[Info   :  Nautilus] Loading v1.0.0.27 for Subnautica
[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000054 (from typeref, class/assembly Atlas, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)
Stack trace:
Nautilus.Patchers.CraftTreePatcher.Patch (HarmonyLib.Harmony harmony) (at <03b551a1b98844cd809c743e49978030>:0)
Nautilus.Initializer..ctor () (at <03b551a1b98844cd809c743e49978030>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.InputSystem.InputSystem:.cctor()

[Info   :   BepInEx] Loading [Defabricator (Purple Edition) 2.0.1]
[Info   :Defabricator (Purple Edition)] Patched
[Info   :   BepInEx] Loading [Configuration Manager 17.1]
[Info   :   BepInEx] Loading [Configuration Manager Tweaks 1.2]
[Info   :   BepInEx] Loading [File Tree 1.0.0]
[Info   :   BepInEx] Loading [BepInEx Tweaks 1.2.1]
[Info   :   BepInEx] Loading [Plugin Doctor 0.1.1]
[Info   :   BepInEx] Loading [SnapBuilder 2.4.0]
[Info   :   BepInEx] Loading [Subnautica Config Handler 1.0.2]
[Info   :   BepInEx] Loading [Unity Audio Patcher 2.0.1]
[Message:   BepInEx] Chainloader startup complete
[Error  : Unity Log] XR: OpenVR Error! OpenVR failed initialization with error code VRInitError_Init_PathRegistryNotFound: "Installation path could not be located (110)"!
[Info   : Unity Log] AddressablesUtility.LoadSceneAsync loading scene: StartScreen in mode Single
[Info   : Unity Log] Initializing Steam services
[Info   : Unity Log] OnQuit behaviour queued for deferred registering, platform services aren't initialized.
[Warning: Unity Log] DontDestroyOnLoad only works for root GameObjects or components on root GameObjects.
[Info   : Unity Log] AddressablesUtility.LoadSceneAsync loading scene: MenuEnvironment in mode Additive
[Info   : Unity Log] Waiting for options to load...
[Info   : Unity Log] RegisterSaveGame: load operation for options was not successful.
[Info   : Unity Log] Waiting for slot0000 to load...
[Info   : Unity Log] RegisterSaveGame: Loading GameInfo for slot0000
[Info   : Unity Log] Loading game settings
[Info   : Unity Log] AddressablesUtility.LoadSceneAsync loading scene: XMenu in mode Additive
[Info   : Unity Log] changeset 71668, QualityLevel = 2
[Info   : Unity Log] OK Running Win64
[Info   : Unity Log] Application version: 1.21.71668
[Info   : Unity Log] SystemInfo: 
 deviceModel = HP EliteBook 865 16 inch G9 Notebook PC (HP)
 deviceName = PC
 deviceType = Desktop
 deviceUniqueIdentifier = ece0e9b4dac028ac41742eb012920cae6fc7749c
 graphicsDeviceID = 5761
 graphicsDeviceName = AMD Radeon(TM) Graphics
 graphicsDeviceType = Direct3D11
 graphicsDeviceVendor = ATI
 graphicsDeviceVendorID = 4098
 graphicsDeviceVersion = Direct3D 11.0 [level 11.1]
 graphicsMemorySize = 16032
 graphicsShaderLevel = 50
 npotSupport = Full
 maxTextureSize = 16384
 operatingSystem = Windows 10  (10.0.19045) 64bit
 processorCount = 16
 processorFrequency = 2695
 processorType = AMD Ryzen 7 PRO 6850U with Radeon Graphics 
 supportedRenderTargetCount = 8
 supports3DTextures = True
 supportsAccelerometer = False
 supportsComputeShaders = True
 supportsGyroscope = False
 supportsImageEffects = True
 supportsInstancing = True
 supportsLocationService = False
 supportsRawShadowDepthSampling = True
 supportsRenderTextures = True
 supportsRenderToCubemap = True
 supportsShadows = True
 supportsSparseTextures = True
 supportsStencil = 1
 supportsVibration = False
 systemMemorySize = 32065

[Info   : Unity Log] Telemetry session started. Platform: 'Steam', UserId: '76561200065573450', SessionId: 361185085

**Comment by RamuneNeptune** [comment]
One of these will be your fix:
- Don't use experimental
- Don't use a pirated copy of the game

**Comment by silvervirus** [comment]
**"FACTS "**

**Comment by MrPurple6411** [comment]
To clarify on this the reason this is occurring is because  UWE made another change on the experimental branch of the game that will break any mod that adds a sprite into the game or even references UWE's old custom sprite system that they now removed like they did in BZ.


And the only people using said branch is people who specifically chose it in steam OR people who download the latest pirate copies as the pirates are constantly cracking the experimental branch so yea ...
