### ISSUE TITLE
Weird values for floats in mod menu

### ISSUE THREAD

**Issue by qqqbbb** [SubnauticaModding/Nautilus#541]
[Screenshot](https://steamcommunity.com/sharedfiles/filedetails/?id=3212137162)

Code to reproduce the behavior:
```
    public class Config : ConfigFile
    {
        [Slider("My multiplier", .1f, 2f, DefaultValue = 1f, Step = .1f, Format = "{0:R0}", Tooltip = "")]
        public float mult = 1f;
    }
```
In the mod menu set the value to 1.3

Nautilus v1.0.0-pre.29

**Comment by JKohlman** [comment]
Not an issue. This is simply [floating point precision errors](https://0.30000000000000004.com/).

Don't use `{0:R0}` if you don't want to display like this, use `{0:0.#}`.
