### ISSUE TITLE
Game freezes/crashes on exit when using an external asset bundle

### ISSUE THREAD

**Issue by 0-F** [SubnauticaModding/Nautilus#543]
My game (Subnautica) freezes/crashes on exit when using an external asset bundle.

I have the Epic Games version of the game. I have the bug with this mod: [Mirror Mod (BepInEx)](https://www.nexusmods.com/subnautica/mods/1334) and with this simple example I made: [example_ExternalAssetBundle](https://github.com/0-F/Subnautica-mods_orax/tree/master/ExternalAssetBundle_ex)
I don't have this bug with Nautilus 1.0.0-pre.23. I have it with Nautilus 1.0.0-pre.24 and newer versions.

1. Craft the custom object with the Habitat Builder.
2. Quit the game.
3. The game will freeze.

**Comment by silvervirus** [comment]
I haven't seen this problem please for provide your log from bepinex/logout.log

**Comment by 0-F** [comment]
Log file when I have the bug: [LogOutput_with_bug.log](https://github.com/SubnauticaModding/Nautilus/files/14967285/LogOutput_with_bug.log)
Log file without the bug: [LogOutput_without_bug.log](https://github.com/SubnauticaModding/Nautilus/files/14967284/LogOutput_without_bug.log)

**Comment by Metious** [comment]
Apologies for the late reply, the two log files you provided are identical and both are using pre.29. Please provide two logs where one has the bug and one doesn't

**Comment by 0-F** [comment]
It seems the bug is fixed in 1.0.0-pre.30.

**Comment by 32Kallies** [comment]
Great. Thank you for the detailed report!
